import type { ApiEnv } from "../config/env.js";

export function createTestEnv(overrides: Partial<ApiEnv> = {}): ApiEnv {
  return {
    apiBaseUrl: "http://localhost:4000",
    appBaseUrl: "http://localhost:3000",
    corsOrigins: ["http://localhost:3000"],
    databaseMaxConnections: 1,
    databaseUrl: "postgres://postgres:postgres@localhost:5432/foodtruckzs_test",
    host: "127.0.0.1",
    jwtAccessSecret: "test-jwt-access-secret-at-least-32-characters",
    jwtAccessTokenTtlSeconds: 900,
    logLevel: "silent",
    nodeEnv: "test",
    port: 0,
    rateLimitAuthMax: 1_000,
    rateLimitAuthWindowMs: 60_000,
    rateLimitMessagingMax: 1_000,
    rateLimitMessagingWindowMs: 60_000,
    rateLimitPaymentCreationMax: 1_000,
    rateLimitPaymentCreationWindowMs: 600_000,
    rateLimitRfqSubmissionMax: 1_000,
    rateLimitRfqSubmissionWindowMs: 600_000,
    refreshTokenSecret: "test-refresh-token-secret-at-least-32-characters",
    refreshTokenTtlDays: 30,
    requestBodyLimitBytes: 1_048_576,
    fileStorageAccessKeyId: "",
    fileStorageBucket: "foodtruckzs-test",
    fileStorageEndpoint: "",
    fileStorageLocalRoot: ".test-storage",
    fileStorageProvider: "local",
    fileStorageRegion: "auto",
    fileStorageSecretAccessKey: "",
    fileStorageSignedUrlTtlSeconds: 900,
    fileStorageSigningSecret: "test-file-storage-secret-at-least-32-characters",
    stripeSecretKey: "sk_test_foodtruckzs",
    stripeWebhookSecret: "whsec_foodtruckzs",
    ...overrides,
  };
}
